/* Generated by JSIL v0.8.2 build 34556. See http://jsil.org/ for more information. */ 
'use strict';
var $asm0C = JSIL.DeclareAssembly("WebOPNotepad, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null");

JSIL.SetEntryPoint($asm0C, $asm0C.TypeRef("WebOPNotepad.WebFormsApplication"), "Main", JSIL.MethodSignature.Action($jsilcore.TypeRef("System.Array", [$asm04.TypeRef("System.String")])));

JSIL.DeclareNamespace("WebOPNotepad");
/* class WebOPNotepad.MainForm */ 

(function MainForm$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize($asm02.ExaPhaser.WebForms.WebForm)) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm01.System.IO.WebStorage.LocalStorageHandle)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.ExaPhaser.WebForms.Controls.TextArea)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm02.ExaPhaser.WebForms.Controls.Button)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm02.ExaPhaser.WebForms.FontStyle)) ();
  };
  var $T05 = function () {
    return ($T05 = JSIL.Memoize($asm02.ExaPhaser.WebForms.Controls.TextControl)) ();
  };
  var $T06 = function () {
    return ($T06 = JSIL.Memoize($asm02.ExaPhaser.WebForms.DelegateCommand)) ();
  };
  var $T07 = function () {
    return ($T07 = JSIL.Memoize($asm04.System.Action)) ();
  };
  var $T08 = function () {
    return ($T08 = JSIL.Memoize($asm02.ExaPhaser.WebForms.Controls.TextBox)) ();
  };
  var $T09 = function () {
    return ($T09 = JSIL.Memoize($asm02.ExaPhaser.WebForms.Layout)) ();
  };
  var $T0A = function () {
    return ($T0A = JSIL.Memoize($asm02.ExaPhaser.WebForms.Controls.TextBlock)) ();
  };
  var $T0B = function () {
    return ($T0B = JSIL.Memoize($asm05.SharpJS.Dom.Styles.TextAlign)) ();
  };
  var $T0C = function () {
    return ($T0C = JSIL.Memoize($asm05.SharpJS.Dom.Styles.FontWeight)) ();
  };
  var $T0D = function () {
    return ($T0D = JSIL.Memoize($asm04.System.Collections.ObjectModel.Collection$b1.Of($asm02.ExaPhaser.WebForms.Control))) ();
  };
  var $T0E = function () {
    return ($T0E = JSIL.Memoize($asm02.ExaPhaser.WebForms.Controls.HtmlControl)) ();
  };
  var $T0F = function () {
    return ($T0F = JSIL.Memoize($asm02.ExaPhaser.WebForms.Control)) ();
  };
  var $T10 = function () {
    return ($T10 = JSIL.Memoize($asm01.System.IO.WebStorage.StorageBase)) ();
  };
  var $T11 = function () {
    return ($T11 = JSIL.Memoize($asm04.System.String)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(JSIL.MethodSignature.Void)) ();
  };
  var $S01 = function () {
    return ($S01 = JSIL.Memoize(JSIL.MethodSignature.Void)) ();
  };
  var $S02 = function () {
    return ($S02 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm02.TypeRef("ExaPhaser.WebForms.Control")]))) ();
  };


  function MainForm__ctor () {
    $T00().prototype._ctor.call(this);
    this._localStorage = new ($T01())();
    var expr_19 = new ($T02())();
    expr_19.set_Text("");
    this.editArea = expr_19;
    var expr_30 = new ($T03())();
    expr_30.set_Text("Save");
    var expr_42 = new ($T04())();
    expr_42.FontStyle$FontSize$value = 12;
    expr_30.set_FontStyle(expr_42);
    expr_30.Button$Command$value = new ($T06())($T07().New(this, null, new JSIL.MethodPointerInfo($thisType, "$l_ctor$gb__6_0", $S00(), false, false)));
    this.saveBtn = expr_30;
    var expr_74 = new ($T03())();
    expr_74.set_Text("Load");
    var expr_86 = new ($T04())();
    expr_86.FontStyle$FontSize$value = 12;
    expr_74.set_FontStyle(expr_86);
    expr_74.Button$Command$value = new ($T06())($T07().New(this, null, new JSIL.MethodPointerInfo($thisType, "$l_ctor$gb__6_1", $S01(), false, false)));
    this.loadBtn = expr_74;
    var expr_B8 = new ($T08())();
    expr_B8.set_Text("Enter a name.");
    this.saveFile = expr_B8;
    var expr_CF = new ($T08())();
    expr_CF.set_Text("Enter an existing file.");
    this.loadFile = expr_CF;
    var expr_E6 = new ($T09())();
    var expr_EC = new ($T0A())();
    expr_EC.set_Text("WebOPNotepad");
    expr_EC.set_TextAlign($T0B().Center);
    var expr_106 = new ($T04())();
    expr_106.FontStyle$FontSize$value = 24;
    expr_106.FontStyle$FontWeight$value = $T0C().Bold;
    expr_EC.set_FontStyle(expr_106);
    $S02().CallVirtual("Add", null, expr_E6, expr_EC);
    $S02().CallVirtual("Add", null, expr_E6, this.editArea);
    $S02().CallVirtual("Add", null, expr_E6, this.saveBtn);
    $S02().CallVirtual("Add", null, expr_E6, this.saveFile);
    $S02().CallVirtual("Add", null, expr_E6, this.loadBtn);
    $S02().CallVirtual("Add", null, expr_E6, this.loadFile);
    var expr_16A = new ($T0A())();
    expr_16A.set_Text("(c) 2016 The WhatCubes Team");
    expr_16A.set_TextAlign($T0B().Center);
    $S02().CallVirtual("Add", null, expr_E6, expr_16A);
    $S02().CallVirtual("Add", null, expr_E6, new ($T0E())());
    this.set_Controls(expr_E6);
    (this.editArea).set_Text(JSIL.Coalesce(this._localStorage._storageHandle.getItem("save_state.txt"), ""));
  }; 

  function MainForm_$l_ctor$gb__6_0 () {
    this.OnSave();
  }; 

  function MainForm_$l_ctor$gb__6_1 () {
    this.OnLoad();
  }; 

  function MainForm_OnLoad () {
    (this.editArea).set_Text(JSIL.Coalesce(this._localStorage._storageHandle.getItem((this.loadFile).get_Text()), ""));
  }; 

  function MainForm_OnSave () {
    this._localStorage._storageHandle.setItem((this.saveFile).get_Text(), (this.editArea).get_Text());
    this._localStorage._storageHandle.setItem("save_state.txt", (this.editArea).get_Text());
  }; 

  JSIL.MakeType({
      BaseType: $asm02.TypeRef("ExaPhaser.WebForms.WebForm"), 
      Name: "WebOPNotepad.MainForm", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      MainForm__ctor
    );

    $.Method({Static:false, Public:false}, "$l.ctor$gb__6_0", 
      JSIL.MethodSignature.Void, 
      MainForm_$l_ctor$gb__6_0
    )
      .Attribute($asm04.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "$l.ctor$gb__6_1", 
      JSIL.MethodSignature.Void, 
      MainForm_$l_ctor$gb__6_1
    )
      .Attribute($asm04.TypeRef("System.Runtime.CompilerServices.CompilerGeneratedAttribute"));

    $.Method({Static:false, Public:false}, "OnLoad", 
      JSIL.MethodSignature.Void, 
      MainForm_OnLoad
    );

    $.Method({Static:false, Public:false}, "OnSave", 
      JSIL.MethodSignature.Void, 
      MainForm_OnSave
    );

    $.Field({Static:false, Public:false}, "saveBtn", $asm02.TypeRef("ExaPhaser.WebForms.Controls.Button"));

    $.Field({Static:false, Public:false}, "loadBtn", $asm02.TypeRef("ExaPhaser.WebForms.Controls.Button"));

    $.Field({Static:false, Public:false}, "saveFile", $asm02.TypeRef("ExaPhaser.WebForms.Controls.TextBox"));

    $.Field({Static:false, Public:false}, "loadFile", $asm02.TypeRef("ExaPhaser.WebForms.Controls.TextBox"));

    $.Field({Static:false, Public:false}, "editArea", $asm02.TypeRef("ExaPhaser.WebForms.Controls.TextArea"));

    $.Field({Static:false, Public:false}, "_localStorage", $asm01.TypeRef("System.IO.WebStorage.LocalStorageHandle"));


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

/* class WebOPNotepad.WebFormsApplication */ 

(function WebFormsApplication$Members () {
  var $, $thisType;
  var $T00 = function () {
    return ($T00 = JSIL.Memoize(System.Array.Of($asm04.System.String))) ();
  };
  var $T01 = function () {
    return ($T01 = JSIL.Memoize($asm02.ExaPhaser.WebForms.WebApplication)) ();
  };
  var $T02 = function () {
    return ($T02 = JSIL.Memoize($asm02.ExaPhaser.WebForms.Themes.CSSUITheme)) ();
  };
  var $T03 = function () {
    return ($T03 = JSIL.Memoize($asm02.ExaPhaser.WebForms.Themes.CSSFramework)) ();
  };
  var $T04 = function () {
    return ($T04 = JSIL.Memoize($asm0C.WebOPNotepad.MainForm)) ();
  };
  var $S00 = function () {
    return ($S00 = JSIL.Memoize(new JSIL.MethodSignature(null, [$asm02.TypeRef("ExaPhaser.WebForms.WebForm"), $asm04.TypeRef("System.String")]))) ();
  };


  function WebFormsApplication__ctor () {
  }; 

  function WebFormsApplication_Main (args) {
    $S00().CallVirtual("Run", null, (new ($T01())(new ($T02())($T03().Kubism))), new ($T04())(), "webform-container");
  }; 

  JSIL.MakeType({
      BaseType: $asm04.TypeRef("System.Object"), 
      Name: "WebOPNotepad.WebFormsApplication", 
      IsPublic: true, 
      IsReferenceType: true, 
      MaximumConstructorArguments: 0, 
    }, function ($ib) {
    $ = $ib;

    $.Method({Static:false, Public:true }, ".ctor", 
      JSIL.MethodSignature.Void, 
      WebFormsApplication__ctor
    );

    $.Method({Static:true , Public:true }, "Main", 
      JSIL.MethodSignature.Action($jsilcore.TypeRef("System.Array", [$.String])), 
      WebFormsApplication_Main
    );


    return function (newThisType) { $thisType = newThisType; }; 
  });

})();

